--  Do not edit. This file is generated by orm_tools automatically.



local g_OrmTmpIndexKey={}
gamescheme = {}

function gamescheme:Init(pDataCenter)
	self.m_pDC = pDataCenter
end

gamescheme.FILEID_NUM = 0


