//  Do not edit. This file is generated by orm_tools automatically.



using System;
using System.Collections.Generic;
using System.Text;
using basetools.DataCenterLite;



[System.Serializable]
public class cfg_Bullet : IDataObj
{
	public int iID;  // 
	public string szName;  // 
	public int iType;  // 
	public string szResPath;  // 
	public float fScale;  // 
	public float fRadius;  // 
	public string szLaunchEffect;  // 
	public float fLaunchEffectTime;  // 
	public string szContinuousEffect;  // 
	public int forwardType;  // 
	public string szHitEffect;  // 
	public int iPenetrate;  // 
	public int iPenetrateCount;  // 
	public int iReflectCount;  // 
	public int iJumCount;  // 
	public float fJumpDistance;  // 
	public float iBoomRadus;  // 
	public float fSpeed;  // 
	public float fMaxSurvivalDistance;  // 
	public float fMaxSurvivalTime;  // 
	public int iFollowLuancher;  // 
	public int iDamageRegionType;  // 
	public float fDamageDistance;  // 
	public float fAngeAndYdis;  // 
	public float fDamageInterval;  // 
	public float fDamageDelay;  // 
	public int iSoundID;  // 
	public int[] param;  // int[5]  

	public IDataObj Clone(){return new cfg_Bullet();}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		szName = pDataChunk.ReadSTRING();
		iType = pDataChunk.ReadINT32();
		szResPath = pDataChunk.ReadSTRING();
		fScale = pDataChunk.ReadFLOAT();
		fRadius = pDataChunk.ReadFLOAT();
		szLaunchEffect = pDataChunk.ReadSTRING();
		fLaunchEffectTime = pDataChunk.ReadFLOAT();
		szContinuousEffect = pDataChunk.ReadSTRING();
		forwardType = pDataChunk.ReadINT32();
		szHitEffect = pDataChunk.ReadSTRING();
		iPenetrate = pDataChunk.ReadINT32();
		iPenetrateCount = pDataChunk.ReadINT32();
		iReflectCount = pDataChunk.ReadINT32();
		iJumCount = pDataChunk.ReadINT32();
		fJumpDistance = pDataChunk.ReadFLOAT();
		iBoomRadus = pDataChunk.ReadFLOAT();
		fSpeed = pDataChunk.ReadFLOAT();
		fMaxSurvivalDistance = pDataChunk.ReadFLOAT();
		fMaxSurvivalTime = pDataChunk.ReadFLOAT();
		iFollowLuancher = pDataChunk.ReadINT32();
		iDamageRegionType = pDataChunk.ReadINT32();
		fDamageDistance = pDataChunk.ReadFLOAT();
		fAngeAndYdis = pDataChunk.ReadFLOAT();
		fDamageInterval = pDataChunk.ReadFLOAT();
		fDamageDelay = pDataChunk.ReadFLOAT();
		iSoundID = pDataChunk.ReadINT32();
		param = pDataChunk.ReadINT32_Array(5);
	}

};

public class cfg_Bullet_idx0 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Bullet_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Bullet_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Bullet_idx0 x = (cfg_Bullet_idx0)_x;
		cfg_Bullet_idx0 y = (cfg_Bullet_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_AI : IDataObj
{
	public uint nID;  // ID
	public string szName;  // 怪物名称
	public int iType;  // AI类型1.定向移动.2.循环施法.3.碰撞自爆.4.按路由点移动
	public int iPriority;  // 执行的优先级.每次都是排他性的只执行一条AI
	public float[] param;  // float[3]  参数

	public IDataObj Clone(){return new cfg_AI();}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadUINT32();
		szName = pDataChunk.ReadSTRING();
		iType = pDataChunk.ReadINT32();
		iPriority = pDataChunk.ReadINT32();
		param = pDataChunk.ReadFLOAT_Array(3);
	}

};

public class cfg_AI_idx0 : IIndexObj
{
	public uint nID;  // ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_AI_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadUINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_AI_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_AI_idx0 x = (cfg_AI_idx0)_x;
		cfg_AI_idx0 y = (cfg_AI_idx0)_y;
		int __iStrTmpCompResult;
		if (x.nID != y.nID) {return (x.nID < y.nID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_Reddot : IDataObj
{
	public int iID;  // 红点ID
	public int[] arrChildren;  // int[-1]  子节点
	public int enShowLimit;  // 显示限制
	public int iPriority;  // 权重
	public int[] arrStyleParams;  // int[-1]  显示风格
	public int bUseSubID;  // 是否使用子ID(程序填)
	public int enFinishMode;  // 完成方式(程序填）
	public string szFinishParams;  // 完成参数(程序填)
	public int iFunctionID;  // 功能ID

	public IDataObj Clone(){return new cfg_Reddot();}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		arrChildren = pDataChunk.ReadINT32_Array(-1);
		enShowLimit = pDataChunk.ReadINT32();
		iPriority = pDataChunk.ReadINT32();
		arrStyleParams = pDataChunk.ReadINT32_Array(-1);
		bUseSubID = pDataChunk.ReadINT32();
		enFinishMode = pDataChunk.ReadINT32();
		szFinishParams = pDataChunk.ReadSTRING();
		iFunctionID = pDataChunk.ReadINT32();
	}

};

public class cfg_Reddot_idx0 : IIndexObj
{
	public int iID;  // 红点ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Reddot_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Reddot_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Reddot_idx0 x = (cfg_Reddot_idx0)_x;
		cfg_Reddot_idx0 y = (cfg_Reddot_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_Icon : IDataObj
{
	public uint nID;  // ID
	public string strIconName;  // 图标名字
	public string strAtlasPath;  // 图集路径（整合在一张图集内）
	public string strIconPath;  // 图标名字

	public IDataObj Clone(){return new cfg_Icon();}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadUINT32();
		strIconName = pDataChunk.ReadSTRING();
		strAtlasPath = pDataChunk.ReadSTRING();
		strIconPath = pDataChunk.ReadSTRING();
	}

};

public class cfg_Icon_idx0 : IIndexObj
{
	public uint nID;  // ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Icon_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadUINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Icon_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Icon_idx0 x = (cfg_Icon_idx0)_x;
		cfg_Icon_idx0 y = (cfg_Icon_idx0)_y;
		int __iStrTmpCompResult;
		if (x.nID != y.nID) {return (x.nID < y.nID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_Buff : IDataObj
{
	public int iID;  // 
	public int buffSign;  // 
	public string buffName;  // 
	public string buffText;  // 
	public int duration;  // 
	public int isUnique;  // 
	public int isBuffUI;  // 
	public int buffIcon;  // 
	public string buffEffect;  // 
	public int isPositive;  // 
	public int isClean;  // 
	public int maxTier;  // 
	public int triggerTiming;  // 
	public float triggerParams;  // 
	public int innerCD;  // 
	public int triggerCount;  // 
	public int targetRule;  // 
	public int targetParams;  // 
	public string commandBuffList;  // 

	public IDataObj Clone(){return new cfg_Buff();}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		buffSign = pDataChunk.ReadINT32();
		buffName = pDataChunk.ReadSTRING();
		buffText = pDataChunk.ReadSTRING();
		duration = pDataChunk.ReadINT32();
		isUnique = pDataChunk.ReadINT32();
		isBuffUI = pDataChunk.ReadINT32();
		buffIcon = pDataChunk.ReadINT32();
		buffEffect = pDataChunk.ReadSTRING();
		isPositive = pDataChunk.ReadINT32();
		isClean = pDataChunk.ReadINT32();
		maxTier = pDataChunk.ReadINT32();
		triggerTiming = pDataChunk.ReadINT32();
		triggerParams = pDataChunk.ReadFLOAT();
		innerCD = pDataChunk.ReadINT32();
		triggerCount = pDataChunk.ReadINT32();
		targetRule = pDataChunk.ReadINT32();
		targetParams = pDataChunk.ReadINT32();
		commandBuffList = pDataChunk.ReadSTRING();
	}

};

public class cfg_Buff_idx0 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Buff_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Buff_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Buff_idx0 x = (cfg_Buff_idx0)_x;
		cfg_Buff_idx0 y = (cfg_Buff_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

public class cfg_Buff_idx1 : IIndexObj
{
	public int iID;  // 
	public int buffSign;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Buff_idx1();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		buffSign = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Buff_idx1_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Buff_idx1 x = (cfg_Buff_idx1)_x;
		cfg_Buff_idx1 y = (cfg_Buff_idx1)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		if (x.buffSign != y.buffSign) {return (x.buffSign < y.buffSign) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_Skill : IDataObj
{
	public int iSkillID;  // 技能ID
	public int iLevel;  // 等级
	public string szName;  // 名字
	public int iIcon;  // 图标
	public string skillSign;  // 技能标识
	public int isHurt;  // 子弹是否造成伤害
	public int isActive;  // 是否主动
	public int isGenAttack;  // 是否普攻（1：普攻;2：技能）
	public float skillCD;  // 技能CD
	public float skillMonRange;  // 技能监测范围
	public float castTime;  // 读条时长
	public string szCastAction;  // 施法动作
	public string triggerEffect;  // 触发特效
	public int triggerTiming;  // 触发时机
	public int triggerParams;  // 触发参数
	public float innerCD;  // 内置CD
	public int triggerCount;  // 最大触发次数
	public string targetRule;  // 选取目标
	public float[] targetParams;  // float[-1]  选取目标参数
	public float[] castPos;  // float[-1]  施法位置
	public int isNeedCastTarget;  // 是否需要选取施法目标
	public int iVisibleType;  // 子弹显示方式(0双方可见，1己方可见，2敌方可见)
	public int iBulletGroupID;  // 子弹组ID
	public string commandSkillList;  // 技能命令效果组合
	public float fDamageRate;  // 子弹伤害系数
	public int iAudioID;  // 攻击音效ID

	public IDataObj Clone(){return new cfg_Skill();}
	public void Load(IDataChunk pDataChunk)
	{
		iSkillID = pDataChunk.ReadINT32();
		iLevel = pDataChunk.ReadINT32();
		szName = pDataChunk.ReadSTRING();
		iIcon = pDataChunk.ReadINT32();
		skillSign = pDataChunk.ReadSTRING();
		isHurt = pDataChunk.ReadINT32();
		isActive = pDataChunk.ReadINT32();
		isGenAttack = pDataChunk.ReadINT32();
		skillCD = pDataChunk.ReadFLOAT();
		skillMonRange = pDataChunk.ReadFLOAT();
		castTime = pDataChunk.ReadFLOAT();
		szCastAction = pDataChunk.ReadSTRING();
		triggerEffect = pDataChunk.ReadSTRING();
		triggerTiming = pDataChunk.ReadINT32();
		triggerParams = pDataChunk.ReadINT32();
		innerCD = pDataChunk.ReadFLOAT();
		triggerCount = pDataChunk.ReadINT32();
		targetRule = pDataChunk.ReadSTRING();
		targetParams = pDataChunk.ReadFLOAT_Array(-1);
		castPos = pDataChunk.ReadFLOAT_Array(-1);
		isNeedCastTarget = pDataChunk.ReadINT32();
		iVisibleType = pDataChunk.ReadINT32();
		iBulletGroupID = pDataChunk.ReadINT32();
		commandSkillList = pDataChunk.ReadSTRING();
		fDamageRate = pDataChunk.ReadFLOAT();
		iAudioID = pDataChunk.ReadINT32();
	}

};

public class cfg_Skill_idx0 : IIndexObj
{
	public int iSkillID;  // 技能ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Skill_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iSkillID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Skill_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Skill_idx0 x = (cfg_Skill_idx0)_x;
		cfg_Skill_idx0 y = (cfg_Skill_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iSkillID != y.iSkillID) {return (x.iSkillID < y.iSkillID) ? -1 :1;} 
		return 0;
	}
}

public class cfg_Skill_idx1 : IIndexObj
{
	public int iSkillID;  // 技能ID
	public int iLevel;  // 等级
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Skill_idx1();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iSkillID = pDataChunk.ReadINT32();
		iLevel = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Skill_idx1_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Skill_idx1 x = (cfg_Skill_idx1)_x;
		cfg_Skill_idx1 y = (cfg_Skill_idx1)_y;
		int __iStrTmpCompResult;
		if (x.iSkillID != y.iSkillID) {return (x.iSkillID < y.iSkillID) ? -1 :1;} 
		if (x.iLevel != y.iLevel) {return (x.iLevel < y.iLevel) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_LightingEffect : IDataObj
{
	public uint nID;  // 光效ID
	public string strResPath;  // 资源路径
	public int iType;  // 光效类型
	public float fScale;  // 缩放比例
	public int bSpineRes;  // 是否为Spine资源(1是/其他不是）
	public string szSpineAnimName;  // Spine动画名称
	public float fMaxLiveTime;  // 最大存活时间
	public sbyte iDisableBindFollow;  // 是否禁止绑定跟随
	public sbyte iNeedQualityCtrl;  // 是否禁用进行画质控制
	public sbyte iNeedQualityCtrlByDistance;  // 是否禁用距离画质控制
	public int[] arrBindOffset;  // int[-1]  绑定点偏移(厘米)
	public string szBindPoint;  // 绑定点名称

	public IDataObj Clone(){return new cfg_LightingEffect();}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadUINT32();
		strResPath = pDataChunk.ReadSTRING();
		iType = pDataChunk.ReadINT32();
		fScale = pDataChunk.ReadFLOAT();
		bSpineRes = pDataChunk.ReadINT32();
		szSpineAnimName = pDataChunk.ReadSTRING();
		fMaxLiveTime = pDataChunk.ReadFLOAT();
		iDisableBindFollow = pDataChunk.ReadINT8();
		iNeedQualityCtrl = pDataChunk.ReadINT8();
		iNeedQualityCtrlByDistance = pDataChunk.ReadINT8();
		arrBindOffset = pDataChunk.ReadINT32_Array(-1);
		szBindPoint = pDataChunk.ReadSTRING();
	}

};

public class cfg_LightingEffect_idx0 : IIndexObj
{
	public uint nID;  // 光效ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_LightingEffect_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadUINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_LightingEffect_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_LightingEffect_idx0 x = (cfg_LightingEffect_idx0)_x;
		cfg_LightingEffect_idx0 y = (cfg_LightingEffect_idx0)_y;
		int __iStrTmpCompResult;
		if (x.nID != y.nID) {return (x.nID < y.nID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_Goods : IDataObj
{
	public int iGoodsID;  // 物品ID
	public string szName;  // 名字
	public int iQuality;  // 物品品质
	public int iSortID;  // 排序ID
	public int iMainClass;  // 物品大类
	public int iSubClass;  // 物品小类
	public int iMinUseLevel;  // 使用等级
	public int iIconID;  // 物品栏图片
	public int iSalesPrice;  // 售价
	public string szDesc;  // 道具描述（废弃）

	public IDataObj Clone(){return new cfg_Goods();}
	public void Load(IDataChunk pDataChunk)
	{
		iGoodsID = pDataChunk.ReadINT32();
		szName = pDataChunk.ReadSTRING();
		iQuality = pDataChunk.ReadINT32();
		iSortID = pDataChunk.ReadINT32();
		iMainClass = pDataChunk.ReadINT32();
		iSubClass = pDataChunk.ReadINT32();
		iMinUseLevel = pDataChunk.ReadINT32();
		iIconID = pDataChunk.ReadINT32();
		iSalesPrice = pDataChunk.ReadINT32();
		szDesc = pDataChunk.ReadSTRING();
	}

};

public class cfg_Goods_idx0 : IIndexObj
{
	public int iGoodsID;  // 物品ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Goods_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iGoodsID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Goods_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Goods_idx0 x = (cfg_Goods_idx0)_x;
		cfg_Goods_idx0 y = (cfg_Goods_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iGoodsID != y.iGoodsID) {return (x.iGoodsID < y.iGoodsID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_Audio : IDataObj
{
	public int ID;  // ID
	public string Desc;  // 描述
	public string assetPath;  // 资源路径
	public int audioType;  // 音效类别标签
	public int loop;  // 是否循环
	public float volume;  // 播放音量大小
	public float pitch;  // 速度变化量
	public float fFadeInTime;  // 渐入时长
	public float fFadeOutTime;  // 渐出时长
	public sbyte i3D;  // 是否为3D音效
	public float fMinDistance;  // 3D音效衰减最小距离
	public float fMaxDistance;  // 3D音效衰减最大距离

	public IDataObj Clone(){return new cfg_Audio();}
	public void Load(IDataChunk pDataChunk)
	{
		ID = pDataChunk.ReadINT32();
		Desc = pDataChunk.ReadSTRING();
		assetPath = pDataChunk.ReadSTRING();
		audioType = pDataChunk.ReadINT32();
		loop = pDataChunk.ReadINT32();
		volume = pDataChunk.ReadFLOAT();
		pitch = pDataChunk.ReadFLOAT();
		fFadeInTime = pDataChunk.ReadFLOAT();
		fFadeOutTime = pDataChunk.ReadFLOAT();
		i3D = pDataChunk.ReadINT8();
		fMinDistance = pDataChunk.ReadFLOAT();
		fMaxDistance = pDataChunk.ReadFLOAT();
	}

};

public class cfg_Audio_idx0 : IIndexObj
{
	public int ID;  // ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Audio_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		ID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Audio_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Audio_idx0 x = (cfg_Audio_idx0)_x;
		cfg_Audio_idx0 y = (cfg_Audio_idx0)_y;
		int __iStrTmpCompResult;
		if (x.ID != y.ID) {return (x.ID < y.ID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_Actor : IDataObj
{
	public int nID;  // ID
	public string szName;  // Actor名称
	public string szResPath;  // 模型路径
	public float fSizeScale;  // 模型缩放

	public IDataObj Clone(){return new cfg_Actor();}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadINT32();
		szName = pDataChunk.ReadSTRING();
		szResPath = pDataChunk.ReadSTRING();
		fSizeScale = pDataChunk.ReadFLOAT();
	}

};

public class cfg_Actor_idx0 : IIndexObj
{
	public int nID;  // ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_Actor_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_Actor_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_Actor_idx0 x = (cfg_Actor_idx0)_x;
		cfg_Actor_idx0 y = (cfg_Actor_idx0)_y;
		int __iStrTmpCompResult;
		if (x.nID != y.nID) {return (x.nID < y.nID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_HeroTeamBuff : IDataObj
{
	public int iID;  // 
	public string szBuffName;  // 
	public string szBuffCls;  // 
	public string szBuffEffect;  // 
	public float[] float3RelativePos;  // float[-1]  
	public int iInterval;  // 
	public int iCount;  // 
	public int iAddHp;  // 
	public int isStackable;  // 
	public int allowDurationReset;  // 

	public IDataObj Clone(){return new cfg_HeroTeamBuff();}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		szBuffName = pDataChunk.ReadSTRING();
		szBuffCls = pDataChunk.ReadSTRING();
		szBuffEffect = pDataChunk.ReadSTRING();
		float3RelativePos = pDataChunk.ReadFLOAT_Array(-1);
		iInterval = pDataChunk.ReadINT32();
		iCount = pDataChunk.ReadINT32();
		iAddHp = pDataChunk.ReadINT32();
		isStackable = pDataChunk.ReadINT32();
		allowDurationReset = pDataChunk.ReadINT32();
	}

};

public class cfg_HeroTeamBuff_idx0 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_HeroTeamBuff_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_HeroTeamBuff_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_HeroTeamBuff_idx0 x = (cfg_HeroTeamBuff_idx0)_x;
		cfg_HeroTeamBuff_idx0 y = (cfg_HeroTeamBuff_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

public class cfg_HeroTeamBuff_idx1 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_HeroTeamBuff_idx1();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_HeroTeamBuff_idx1_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_HeroTeamBuff_idx1 x = (cfg_HeroTeamBuff_idx1)_x;
		cfg_HeroTeamBuff_idx1 y = (cfg_HeroTeamBuff_idx1)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_HeroTeamSkills : IDataObj
{
	public int iID;  // 
	public string szName;  // 
	public string szAnimName;  // 
	public int iType;  // 
	public int iRange;  // 
	public int iValue;  // 
	public int iPercentValue;  // 
	public int iAbnormalTime;  // 
	public int iHate;  // 
	public int iSkillCD;  // 
	public string szChat;  // 
	public int hasSkillTip;  // 
	public int iSkillTipTime;  // 
	public int iSkillTipPrefabID;  // 
	public string szVfxResPath;  // 

	public IDataObj Clone(){return new cfg_HeroTeamSkills();}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		szName = pDataChunk.ReadSTRING();
		szAnimName = pDataChunk.ReadSTRING();
		iType = pDataChunk.ReadINT32();
		iRange = pDataChunk.ReadINT32();
		iValue = pDataChunk.ReadINT32();
		iPercentValue = pDataChunk.ReadINT32();
		iAbnormalTime = pDataChunk.ReadINT32();
		iHate = pDataChunk.ReadINT32();
		iSkillCD = pDataChunk.ReadINT32();
		szChat = pDataChunk.ReadSTRING();
		hasSkillTip = pDataChunk.ReadINT32();
		iSkillTipTime = pDataChunk.ReadINT32();
		iSkillTipPrefabID = pDataChunk.ReadINT32();
		szVfxResPath = pDataChunk.ReadSTRING();
	}

};

public class cfg_HeroTeamSkills_idx0 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_HeroTeamSkills_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_HeroTeamSkills_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_HeroTeamSkills_idx0 x = (cfg_HeroTeamSkills_idx0)_x;
		cfg_HeroTeamSkills_idx0 y = (cfg_HeroTeamSkills_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

public class cfg_HeroTeamSkills_idx1 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_HeroTeamSkills_idx1();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_HeroTeamSkills_idx1_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_HeroTeamSkills_idx1 x = (cfg_HeroTeamSkills_idx1)_x;
		cfg_HeroTeamSkills_idx1 y = (cfg_HeroTeamSkills_idx1)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_ActorAnimConfig : IDataObj
{
	public int iID;  // 
	public string szName;  // 
	public string szSpineFile;  // 
	public string szIdle;  // 
	public string szAttack;  // 
	public string szHit;  // 
	public string szJump1;  // 
	public string szJump2;  // 
	public string szWin;  // 
	public string szKnockuped;  // 
	public string szStand;  // 
	public string szDeath;  // 
	public string szMove;  // 

	public IDataObj Clone(){return new cfg_ActorAnimConfig();}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		szName = pDataChunk.ReadSTRING();
		szSpineFile = pDataChunk.ReadSTRING();
		szIdle = pDataChunk.ReadSTRING();
		szAttack = pDataChunk.ReadSTRING();
		szHit = pDataChunk.ReadSTRING();
		szJump1 = pDataChunk.ReadSTRING();
		szJump2 = pDataChunk.ReadSTRING();
		szWin = pDataChunk.ReadSTRING();
		szKnockuped = pDataChunk.ReadSTRING();
		szStand = pDataChunk.ReadSTRING();
		szDeath = pDataChunk.ReadSTRING();
		szMove = pDataChunk.ReadSTRING();
	}

};

public class cfg_ActorAnimConfig_idx0 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_ActorAnimConfig_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_ActorAnimConfig_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_ActorAnimConfig_idx0 x = (cfg_ActorAnimConfig_idx0)_x;
		cfg_ActorAnimConfig_idx0 y = (cfg_ActorAnimConfig_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_HeroTeamBullet : IDataObj
{
	public int iID;  // 
	public string szName;  // 
	public int iType;  // 
	public string szResPath;  // 
	public float fScale;  // 
	public float fRadius;  // 
	public string szHitEffect;  // 
	public float fSpeed;  // 

	public IDataObj Clone(){return new cfg_HeroTeamBullet();}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		szName = pDataChunk.ReadSTRING();
		iType = pDataChunk.ReadINT32();
		szResPath = pDataChunk.ReadSTRING();
		fScale = pDataChunk.ReadFLOAT();
		fRadius = pDataChunk.ReadFLOAT();
		szHitEffect = pDataChunk.ReadSTRING();
		fSpeed = pDataChunk.ReadFLOAT();
	}

};

public class cfg_HeroTeamBullet_idx0 : IIndexObj
{
	public int iID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_HeroTeamBullet_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_HeroTeamBullet_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_HeroTeamBullet_idx0 x = (cfg_HeroTeamBullet_idx0)_x;
		cfg_HeroTeamBullet_idx0 y = (cfg_HeroTeamBullet_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iID != y.iID) {return (x.iID < y.iID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_HeroTeamLevels : IDataObj
{
	public int iChapterID;  // 
	public int iLevelID;  // 
	public int iBossID;  // 
	public float[] aryBossBornPos;  // float[-1]  
	public int iBossBornDelaySeconds;  // 
	public int iNpcID;  // 
	public float[] aryNpcBornPos;  // float[-1]  
	public int[] aryHerosBornPos;  // int[-1]  
	public int iLeaderIndex;  // 
	public float fLeaderModeScale;  // 
	public int[] aryOuterRingStance;  // int[-1]  
	public int[] aryInnerCircleStanding;  // int[-1]  
	public int[] aryTankStanding;  // int[-1]  
	public int iGoodsID;  // 
	public int iDropID;  // 

	public IDataObj Clone(){return new cfg_HeroTeamLevels();}
	public void Load(IDataChunk pDataChunk)
	{
		iChapterID = pDataChunk.ReadINT32();
		iLevelID = pDataChunk.ReadINT32();
		iBossID = pDataChunk.ReadINT32();
		aryBossBornPos = pDataChunk.ReadFLOAT_Array(-1);
		iBossBornDelaySeconds = pDataChunk.ReadINT32();
		iNpcID = pDataChunk.ReadINT32();
		aryNpcBornPos = pDataChunk.ReadFLOAT_Array(-1);
		aryHerosBornPos = pDataChunk.ReadINT32_Array(-1);
		iLeaderIndex = pDataChunk.ReadINT32();
		fLeaderModeScale = pDataChunk.ReadFLOAT();
		aryOuterRingStance = pDataChunk.ReadINT32_Array(-1);
		aryInnerCircleStanding = pDataChunk.ReadINT32_Array(-1);
		aryTankStanding = pDataChunk.ReadINT32_Array(-1);
		iGoodsID = pDataChunk.ReadINT32();
		iDropID = pDataChunk.ReadINT32();
	}

};

public class cfg_HeroTeamLevels_idx0 : IIndexObj
{
	public int iChapterID;  // 
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_HeroTeamLevels_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		iChapterID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_HeroTeamLevels_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_HeroTeamLevels_idx0 x = (cfg_HeroTeamLevels_idx0)_x;
		cfg_HeroTeamLevels_idx0 y = (cfg_HeroTeamLevels_idx0)_y;
		int __iStrTmpCompResult;
		if (x.iChapterID != y.iChapterID) {return (x.iChapterID < y.iChapterID) ? -1 :1;} 
		return 0;
	}
}

[System.Serializable]
public class cfg_HeroTeamCreature : IDataObj
{
	public int nID;  // ID
	public int HeroClass;  // 角色职业（ 0: 其它； 1：近战坦克； 2：近战输出； 3：远程输出； 4：远程治疗；）
	public int AttackType;  // 攻击方式（0:近战；1:远程；2:奶爸/奶妈；3:二五仔(混合型) ）
	public int iBullet;  // 远程职业，子弹的皮肤
	public string szShotBone;  // 远程职业，子弹发射的骨骼
	public int baseHP;  // 生命
	public float fAttackInterval;  // 攻击间隔，每多少秒攻击1次
	public int iAttack;  // 攻击力
	public string szAttackEffectPath;  // 攻击特效路径
	public int iAttkBuffID;  // 普通攻击Buff
	public float fMoveSpeed;  // 移动速度
	public int[] Skills;  // int[-1]  技能列表
	public int iAttackHatred;  // 攻击/治疗 仇恨值 百分比

	public IDataObj Clone(){return new cfg_HeroTeamCreature();}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadINT32();
		HeroClass = pDataChunk.ReadINT32();
		AttackType = pDataChunk.ReadINT32();
		iBullet = pDataChunk.ReadINT32();
		szShotBone = pDataChunk.ReadSTRING();
		baseHP = pDataChunk.ReadINT32();
		fAttackInterval = pDataChunk.ReadFLOAT();
		iAttack = pDataChunk.ReadINT32();
		szAttackEffectPath = pDataChunk.ReadSTRING();
		iAttkBuffID = pDataChunk.ReadINT32();
		fMoveSpeed = pDataChunk.ReadFLOAT();
		Skills = pDataChunk.ReadINT32_Array(-1);
		iAttackHatred = pDataChunk.ReadINT32();
	}

};

public class cfg_HeroTeamCreature_idx0 : IIndexObj
{
	public int nID;  // ID
	public uint __dataarea_offset__;  // 

	public IDataObj Clone(){return new cfg_HeroTeamCreature_idx0();}
	public uint GetDataPosition(){return __dataarea_offset__;}
	public void Load(IDataChunk pDataChunk)
	{
		nID = pDataChunk.ReadINT32();
		__dataarea_offset__ = pDataChunk.ReadUINT32();
	}

};

class cfg_HeroTeamCreature_idx0_cmper : IComparer<IIndexObj>
{
	public int Compare(IIndexObj _x, IIndexObj _y)
	{
		cfg_HeroTeamCreature_idx0 x = (cfg_HeroTeamCreature_idx0)_x;
		cfg_HeroTeamCreature_idx0 y = (cfg_HeroTeamCreature_idx0)_y;
		int __iStrTmpCompResult;
		if (x.nID != y.nID) {return (x.nID < y.nID) ? -1 :1;} 
		return 0;
	}
}



//////////////////////////////////////////////////////////////////////////


public interface Igamescheme
{
	cfg_Bullet Bullet(int iIndex);
	int Bullet_nums();
	cfg_Bullet Bullet_0(int iID);
	cfg_AI AI(int iIndex);
	int AI_nums();
	cfg_AI AI_0(uint nID);
	cfg_Reddot Reddot(int iIndex);
	int Reddot_nums();
	cfg_Reddot Reddot_0(int iID);
	cfg_Icon Icon(int iIndex);
	int Icon_nums();
	cfg_Icon Icon_0(uint nID);
	cfg_Buff Buff(int iIndex);
	int Buff_nums();
	cfg_Buff Buff_0(int iID);
	cfg_Buff Buff_1(int iID, int buffSign);
	cfg_Skill Skill(int iIndex);
	int Skill_nums();
	cfg_Skill Skill_0(int iSkillID);
	cfg_Skill Skill_1(int iSkillID, int iLevel);
	cfg_LightingEffect LightingEffect(int iIndex);
	int LightingEffect_nums();
	cfg_LightingEffect LightingEffect_0(uint nID);
	cfg_Goods Goods(int iIndex);
	int Goods_nums();
	cfg_Goods Goods_0(int iGoodsID);
	cfg_Audio Audio(int iIndex);
	int Audio_nums();
	cfg_Audio Audio_0(int ID);
	cfg_Actor Actor(int iIndex);
	int Actor_nums();
	cfg_Actor Actor_0(int nID);
	cfg_HeroTeamBuff HeroTeamBuff(int iIndex);
	int HeroTeamBuff_nums();
	cfg_HeroTeamBuff HeroTeamBuff_0(int iID);
	cfg_HeroTeamBuff HeroTeamBuff_1(int iID);
	cfg_HeroTeamSkills HeroTeamSkills(int iIndex);
	int HeroTeamSkills_nums();
	cfg_HeroTeamSkills HeroTeamSkills_0(int iID);
	cfg_HeroTeamSkills HeroTeamSkills_1(int iID);
	cfg_ActorAnimConfig ActorAnimConfig(int iIndex);
	int ActorAnimConfig_nums();
	cfg_ActorAnimConfig ActorAnimConfig_0(int iID);
	cfg_HeroTeamBullet HeroTeamBullet(int iIndex);
	int HeroTeamBullet_nums();
	cfg_HeroTeamBullet HeroTeamBullet_0(int iID);
	cfg_HeroTeamLevels HeroTeamLevels(int iIndex);
	int HeroTeamLevels_nums();
	cfg_HeroTeamLevels HeroTeamLevels_0(int iChapterID);
	cfg_HeroTeamCreature HeroTeamCreature(int iIndex);
	int HeroTeamCreature_nums();
	cfg_HeroTeamCreature HeroTeamCreature_0(int nID);
}   // interface



//////////////////////////////////////////////////////////////////////////


public class Cgamescheme : Igamescheme
{
	private IDataCenterLite m_pDataCenter;
	public System.Text.Encoding m_pStrEncoding = Encoding.UTF8; 
	public enum EnFileID
	{
		Bullet = 0,
		AI = 1,
		Reddot = 2,
		Icon = 3,
		Buff = 4,
		Skill = 5,
		LightingEffect = 6,
		Goods = 7,
		Audio = 8,
		Actor = 9,
		HeroTeamBuff = 10,
		HeroTeamSkills = 11,
		ActorAnimConfig = 12,
		HeroTeamBullet = 13,
		HeroTeamLevels = 14,
		HeroTeamCreature = 15,
	}

	public static int byteStrcmp(byte[] x, byte[] y){	int x_len = x.Length;	int y_len = y.Length;	int iCount = Math.Min(x_len, y_len);	for (int i = 0; i < iCount; ++i){		if (x[i] != y[i]){return x[i] < y[i] ? -1 : 1;}	}	if (x_len == y_len) { return 0; }	return x_len < y_len ? -1 : 1;}
	//  ���ִ��ʧ��, ����IDataCenterLite::GetLastError()��ȡ������Ϣ
	public bool Create(IDataCenterLite pDataCenter)
	{
		m_pDataCenter = pDataCenter;

		{
			IIndexObj[] arrKeys ={new cfg_Bullet_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Bullet_idx0_cmper()};
			if (!pDataCenter.LoadData(0, new cfg_Bullet(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_AI_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_AI_idx0_cmper()};
			if (!pDataCenter.LoadData(1, new cfg_AI(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_Reddot_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Reddot_idx0_cmper()};
			if (!pDataCenter.LoadData(2, new cfg_Reddot(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_Icon_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Icon_idx0_cmper()};
			if (!pDataCenter.LoadData(3, new cfg_Icon(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_Buff_idx0(),new cfg_Buff_idx1()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Buff_idx0_cmper(),new cfg_Buff_idx1_cmper()};
			if (!pDataCenter.LoadData(4, new cfg_Buff(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_Skill_idx0(),new cfg_Skill_idx1()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Skill_idx0_cmper(),new cfg_Skill_idx1_cmper()};
			if (!pDataCenter.LoadData(5, new cfg_Skill(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_LightingEffect_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_LightingEffect_idx0_cmper()};
			if (!pDataCenter.LoadData(6, new cfg_LightingEffect(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_Goods_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Goods_idx0_cmper()};
			if (!pDataCenter.LoadData(7, new cfg_Goods(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_Audio_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Audio_idx0_cmper()};
			if (!pDataCenter.LoadData(8, new cfg_Audio(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_Actor_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_Actor_idx0_cmper()};
			if (!pDataCenter.LoadData(9, new cfg_Actor(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_HeroTeamBuff_idx0(),new cfg_HeroTeamBuff_idx1()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_HeroTeamBuff_idx0_cmper(),new cfg_HeroTeamBuff_idx1_cmper()};
			if (!pDataCenter.LoadData(10, new cfg_HeroTeamBuff(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_HeroTeamSkills_idx0(),new cfg_HeroTeamSkills_idx1()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_HeroTeamSkills_idx0_cmper(),new cfg_HeroTeamSkills_idx1_cmper()};
			if (!pDataCenter.LoadData(11, new cfg_HeroTeamSkills(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_ActorAnimConfig_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_ActorAnimConfig_idx0_cmper()};
			if (!pDataCenter.LoadData(12, new cfg_ActorAnimConfig(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_HeroTeamBullet_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_HeroTeamBullet_idx0_cmper()};
			if (!pDataCenter.LoadData(13, new cfg_HeroTeamBullet(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_HeroTeamLevels_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_HeroTeamLevels_idx0_cmper()};
			if (!pDataCenter.LoadData(14, new cfg_HeroTeamLevels(), arrKeys, arrCmper)) return false;
		}
		{
			IIndexObj[] arrKeys ={new cfg_HeroTeamCreature_idx0()};
			IComparer<IIndexObj>[] arrCmper ={new cfg_HeroTeamCreature_idx0_cmper()};
			if (!pDataCenter.LoadData(15, new cfg_HeroTeamCreature(), arrKeys, arrCmper)) return false;
		}
		return true;
	}

	public cfg_Bullet Bullet(int iIndex){return (cfg_Bullet)m_pDataCenter.GetRecordByIndex(0, (uint)iIndex);}
	public int Bullet_nums(){return m_pDataCenter.GetFileRecordNums(0);}
	private cfg_Bullet_idx0 m_cfg_Bullet_idx0 = new cfg_Bullet_idx0();
	public cfg_Bullet Bullet_0(int _iID){
		m_cfg_Bullet_idx0.iID = _iID;
		return (cfg_Bullet)m_pDataCenter.GetRecord(0, 0, m_cfg_Bullet_idx0);
	}
	public cfg_AI AI(int iIndex){return (cfg_AI)m_pDataCenter.GetRecordByIndex(1, (uint)iIndex);}
	public int AI_nums(){return m_pDataCenter.GetFileRecordNums(1);}
	private cfg_AI_idx0 m_cfg_AI_idx0 = new cfg_AI_idx0();
	public cfg_AI AI_0(uint _nID){
		m_cfg_AI_idx0.nID = _nID;
		return (cfg_AI)m_pDataCenter.GetRecord(1, 0, m_cfg_AI_idx0);
	}
	public cfg_Reddot Reddot(int iIndex){return (cfg_Reddot)m_pDataCenter.GetRecordByIndex(2, (uint)iIndex);}
	public int Reddot_nums(){return m_pDataCenter.GetFileRecordNums(2);}
	private cfg_Reddot_idx0 m_cfg_Reddot_idx0 = new cfg_Reddot_idx0();
	public cfg_Reddot Reddot_0(int _iID){
		m_cfg_Reddot_idx0.iID = _iID;
		return (cfg_Reddot)m_pDataCenter.GetRecord(2, 0, m_cfg_Reddot_idx0);
	}
	public cfg_Icon Icon(int iIndex){return (cfg_Icon)m_pDataCenter.GetRecordByIndex(3, (uint)iIndex);}
	public int Icon_nums(){return m_pDataCenter.GetFileRecordNums(3);}
	private cfg_Icon_idx0 m_cfg_Icon_idx0 = new cfg_Icon_idx0();
	public cfg_Icon Icon_0(uint _nID){
		m_cfg_Icon_idx0.nID = _nID;
		return (cfg_Icon)m_pDataCenter.GetRecord(3, 0, m_cfg_Icon_idx0);
	}
	public cfg_Buff Buff(int iIndex){return (cfg_Buff)m_pDataCenter.GetRecordByIndex(4, (uint)iIndex);}
	public int Buff_nums(){return m_pDataCenter.GetFileRecordNums(4);}
	private cfg_Buff_idx0 m_cfg_Buff_idx0 = new cfg_Buff_idx0();
	public cfg_Buff Buff_0(int _iID){
		m_cfg_Buff_idx0.iID = _iID;
		return (cfg_Buff)m_pDataCenter.GetRecord(4, 0, m_cfg_Buff_idx0);
	}
	private cfg_Buff_idx1 m_cfg_Buff_idx1 = new cfg_Buff_idx1();
	public cfg_Buff Buff_1(int _iID, int _buffSign){
		m_cfg_Buff_idx1.iID = _iID;
		m_cfg_Buff_idx1.buffSign = _buffSign;
		return (cfg_Buff)m_pDataCenter.GetRecord(4, 1, m_cfg_Buff_idx1);
	}
	public cfg_Skill Skill(int iIndex){return (cfg_Skill)m_pDataCenter.GetRecordByIndex(5, (uint)iIndex);}
	public int Skill_nums(){return m_pDataCenter.GetFileRecordNums(5);}
	private cfg_Skill_idx0 m_cfg_Skill_idx0 = new cfg_Skill_idx0();
	public cfg_Skill Skill_0(int _iSkillID){
		m_cfg_Skill_idx0.iSkillID = _iSkillID;
		return (cfg_Skill)m_pDataCenter.GetRecord(5, 0, m_cfg_Skill_idx0);
	}
	private cfg_Skill_idx1 m_cfg_Skill_idx1 = new cfg_Skill_idx1();
	public cfg_Skill Skill_1(int _iSkillID, int _iLevel){
		m_cfg_Skill_idx1.iSkillID = _iSkillID;
		m_cfg_Skill_idx1.iLevel = _iLevel;
		return (cfg_Skill)m_pDataCenter.GetRecord(5, 1, m_cfg_Skill_idx1);
	}
	public cfg_LightingEffect LightingEffect(int iIndex){return (cfg_LightingEffect)m_pDataCenter.GetRecordByIndex(6, (uint)iIndex);}
	public int LightingEffect_nums(){return m_pDataCenter.GetFileRecordNums(6);}
	private cfg_LightingEffect_idx0 m_cfg_LightingEffect_idx0 = new cfg_LightingEffect_idx0();
	public cfg_LightingEffect LightingEffect_0(uint _nID){
		m_cfg_LightingEffect_idx0.nID = _nID;
		return (cfg_LightingEffect)m_pDataCenter.GetRecord(6, 0, m_cfg_LightingEffect_idx0);
	}
	public cfg_Goods Goods(int iIndex){return (cfg_Goods)m_pDataCenter.GetRecordByIndex(7, (uint)iIndex);}
	public int Goods_nums(){return m_pDataCenter.GetFileRecordNums(7);}
	private cfg_Goods_idx0 m_cfg_Goods_idx0 = new cfg_Goods_idx0();
	public cfg_Goods Goods_0(int _iGoodsID){
		m_cfg_Goods_idx0.iGoodsID = _iGoodsID;
		return (cfg_Goods)m_pDataCenter.GetRecord(7, 0, m_cfg_Goods_idx0);
	}
	public cfg_Audio Audio(int iIndex){return (cfg_Audio)m_pDataCenter.GetRecordByIndex(8, (uint)iIndex);}
	public int Audio_nums(){return m_pDataCenter.GetFileRecordNums(8);}
	private cfg_Audio_idx0 m_cfg_Audio_idx0 = new cfg_Audio_idx0();
	public cfg_Audio Audio_0(int _ID){
		m_cfg_Audio_idx0.ID = _ID;
		return (cfg_Audio)m_pDataCenter.GetRecord(8, 0, m_cfg_Audio_idx0);
	}
	public cfg_Actor Actor(int iIndex){return (cfg_Actor)m_pDataCenter.GetRecordByIndex(9, (uint)iIndex);}
	public int Actor_nums(){return m_pDataCenter.GetFileRecordNums(9);}
	private cfg_Actor_idx0 m_cfg_Actor_idx0 = new cfg_Actor_idx0();
	public cfg_Actor Actor_0(int _nID){
		m_cfg_Actor_idx0.nID = _nID;
		return (cfg_Actor)m_pDataCenter.GetRecord(9, 0, m_cfg_Actor_idx0);
	}
	public cfg_HeroTeamBuff HeroTeamBuff(int iIndex){return (cfg_HeroTeamBuff)m_pDataCenter.GetRecordByIndex(10, (uint)iIndex);}
	public int HeroTeamBuff_nums(){return m_pDataCenter.GetFileRecordNums(10);}
	private cfg_HeroTeamBuff_idx0 m_cfg_HeroTeamBuff_idx0 = new cfg_HeroTeamBuff_idx0();
	public cfg_HeroTeamBuff HeroTeamBuff_0(int _iID){
		m_cfg_HeroTeamBuff_idx0.iID = _iID;
		return (cfg_HeroTeamBuff)m_pDataCenter.GetRecord(10, 0, m_cfg_HeroTeamBuff_idx0);
	}
	private cfg_HeroTeamBuff_idx1 m_cfg_HeroTeamBuff_idx1 = new cfg_HeroTeamBuff_idx1();
	public cfg_HeroTeamBuff HeroTeamBuff_1(int _iID){
		m_cfg_HeroTeamBuff_idx1.iID = _iID;
		return (cfg_HeroTeamBuff)m_pDataCenter.GetRecord(10, 1, m_cfg_HeroTeamBuff_idx1);
	}
	public cfg_HeroTeamSkills HeroTeamSkills(int iIndex){return (cfg_HeroTeamSkills)m_pDataCenter.GetRecordByIndex(11, (uint)iIndex);}
	public int HeroTeamSkills_nums(){return m_pDataCenter.GetFileRecordNums(11);}
	private cfg_HeroTeamSkills_idx0 m_cfg_HeroTeamSkills_idx0 = new cfg_HeroTeamSkills_idx0();
	public cfg_HeroTeamSkills HeroTeamSkills_0(int _iID){
		m_cfg_HeroTeamSkills_idx0.iID = _iID;
		return (cfg_HeroTeamSkills)m_pDataCenter.GetRecord(11, 0, m_cfg_HeroTeamSkills_idx0);
	}
	private cfg_HeroTeamSkills_idx1 m_cfg_HeroTeamSkills_idx1 = new cfg_HeroTeamSkills_idx1();
	public cfg_HeroTeamSkills HeroTeamSkills_1(int _iID){
		m_cfg_HeroTeamSkills_idx1.iID = _iID;
		return (cfg_HeroTeamSkills)m_pDataCenter.GetRecord(11, 1, m_cfg_HeroTeamSkills_idx1);
	}
	public cfg_ActorAnimConfig ActorAnimConfig(int iIndex){return (cfg_ActorAnimConfig)m_pDataCenter.GetRecordByIndex(12, (uint)iIndex);}
	public int ActorAnimConfig_nums(){return m_pDataCenter.GetFileRecordNums(12);}
	private cfg_ActorAnimConfig_idx0 m_cfg_ActorAnimConfig_idx0 = new cfg_ActorAnimConfig_idx0();
	public cfg_ActorAnimConfig ActorAnimConfig_0(int _iID){
		m_cfg_ActorAnimConfig_idx0.iID = _iID;
		return (cfg_ActorAnimConfig)m_pDataCenter.GetRecord(12, 0, m_cfg_ActorAnimConfig_idx0);
	}
	public cfg_HeroTeamBullet HeroTeamBullet(int iIndex){return (cfg_HeroTeamBullet)m_pDataCenter.GetRecordByIndex(13, (uint)iIndex);}
	public int HeroTeamBullet_nums(){return m_pDataCenter.GetFileRecordNums(13);}
	private cfg_HeroTeamBullet_idx0 m_cfg_HeroTeamBullet_idx0 = new cfg_HeroTeamBullet_idx0();
	public cfg_HeroTeamBullet HeroTeamBullet_0(int _iID){
		m_cfg_HeroTeamBullet_idx0.iID = _iID;
		return (cfg_HeroTeamBullet)m_pDataCenter.GetRecord(13, 0, m_cfg_HeroTeamBullet_idx0);
	}
	public cfg_HeroTeamLevels HeroTeamLevels(int iIndex){return (cfg_HeroTeamLevels)m_pDataCenter.GetRecordByIndex(14, (uint)iIndex);}
	public int HeroTeamLevels_nums(){return m_pDataCenter.GetFileRecordNums(14);}
	private cfg_HeroTeamLevels_idx0 m_cfg_HeroTeamLevels_idx0 = new cfg_HeroTeamLevels_idx0();
	public cfg_HeroTeamLevels HeroTeamLevels_0(int _iChapterID){
		m_cfg_HeroTeamLevels_idx0.iChapterID = _iChapterID;
		return (cfg_HeroTeamLevels)m_pDataCenter.GetRecord(14, 0, m_cfg_HeroTeamLevels_idx0);
	}
	public cfg_HeroTeamCreature HeroTeamCreature(int iIndex){return (cfg_HeroTeamCreature)m_pDataCenter.GetRecordByIndex(15, (uint)iIndex);}
	public int HeroTeamCreature_nums(){return m_pDataCenter.GetFileRecordNums(15);}
	private cfg_HeroTeamCreature_idx0 m_cfg_HeroTeamCreature_idx0 = new cfg_HeroTeamCreature_idx0();
	public cfg_HeroTeamCreature HeroTeamCreature_0(int _nID){
		m_cfg_HeroTeamCreature_idx0.nID = _nID;
		return (cfg_HeroTeamCreature)m_pDataCenter.GetRecord(15, 0, m_cfg_HeroTeamCreature_idx0);
	}
}   //   class Cgamescheme

